"""
📦 Exporta datasets para formato Node.js
Converte JSON Python para módulos ES6 prontos para importar
"""

import json
from pathlib import Path

class BackendExporter:
    def __init__(self):
        self.datasets_dir = Path("datasets/processed")
        self.backend_dir = Path("../backend/src/data")  # Pasta no backend
        self.backend_dir.mkdir(parents=True, exist_ok=True)
    
    def export_as_js_module(self, data: dict, filename: str):
        """Converte JSON para módulo ES6"""
        js_content = f"""/**
 * 🤖 Auto-generated by ML Engine
 * Dataset: {filename}
 * DO NOT EDIT MANUALLY
 */

export const {filename.replace('.', '_')} = {json.dumps(data, ensure_ascii=False, indent=2)};

export default {filename.replace('.', '_')};
"""
        
        output_file = self.backend_dir / f"{filename}.js"
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(js_content)
        
        return output_file
    
    def create_index_file(self, exported_files: list):
        """Cria arquivo index.js para importar tudo"""
        imports = []
        exports = []
        
        for file in exported_files:
            name = file.stem
            imports.append(f"import {name} from './{name}.js';")
            exports.append(name)
        
        index_content = f"""/**
 * 🤖 CV Builder - ML Datasets Index
 * Centraliza todos os datasets para uso no backend
 */

{chr(10).join(imports)}

export {{
  {', '.join(exports)}
}};

// Helper: buscar skill por nome
export const findSkill = (skillName, area = null) => {{
  const db = skills_database;
  
  if (area && db[area]) {{
    for (const category in db[area]) {{
      const found = db[area][category].find(s => 
        s.name.toLowerCase() === skillName.toLowerCase()
      );
      if (found) return found;
    }}
  }}
  
  // Buscar em todas as áreas
  for (const area in db) {{
    for (const category in db[area]) {{
      const found = db[area][category].find(s => 
        s.name.toLowerCase() === skillName.toLowerCase()
      );
      if (found) return found;
    }}
  }}
  
  return null;
}};

// Helper: obter keywords ATS por área
export const getATSKeywords = (area) => {{
  return ats_keywords[area] || {{}};
}};

// Helper: encontrar exemplo de melhoria
export const findImprovementExample = (section) => {{
  return text_improvement.filter(item => item.section === section);
}};
"""
        
        index_file = self.backend_dir / "index.js"
        with open(index_file, "w", encoding="utf-8") as f:
            f.write(index_content)
        
        return index_file
    
    def export_all(self):
        """Exporta todos os datasets"""
        print("📦 Iniciando exportação para backend...\n")
        
        exported_files = []
        
        # Listar todos os JSONs processados
        for json_file in self.datasets_dir.glob("*.json"):
            print(f"📄 Processando {json_file.name}...")
            
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            
            # Exportar como módulo JS
            output = self.export_as_js_module(data, json_file.stem)
            exported_files.append(output)
            print(f"   ✅ Exportado para {output.relative_to(self.backend_dir.parent.parent)}")
        
        # Criar index.js
        print("\n📝 Criando index.js...")
        index_file = self.create_index_file(exported_files)
        print(f"   ✅ Index criado em {index_file.relative_to(self.backend_dir.parent.parent)}")
        
        print(f"\n✨ Exportação concluída!")
        print(f"📁 {len(exported_files)} arquivos exportados para: {self.backend_dir.absolute()}")
        print("\n🔥 Uso no backend:")
        print("   import { skills_database, text_improvement } from './src/data/index.js';")

if __name__ == "__main__":
    exporter = BackendExporter()
    exporter.export_all()